//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDICAL_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntakeTime
    {
        public int IntakeTimeId { get; set; }
        public int PrescriptionsId { get; set; }
        public int Day { get; set; }
        public int Hour { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Prescriptions Prescriptions { get; set; }
    }
}
